import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar'
import Image from './components/Image'
import Title_Info from './components/Title_Info'
import Scorebord from './components/Scorebord'
import Detail from './components/Details'
import Footer from './components/Footer'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://code.iconify.design/2/2.1.2/iconify.min.js"></script>
        {/* <script src="https://code.iconify.design/2/2.1.2/iconify.min.js"></script> */}
      </Head>
      <div>
        <Navbar />
        <Image />
        <Title_Info />
        <Detail />
        <Footer />

      </div>
    </div>
  )
}
